#

services:
  api_proxy:
    build: .
    image: safe-proxy-docker
    volumes:
      - secret-key-volume:/docker-volume
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app:ro
      - type: tmpfs
        target: /tmpfs
    networks:
      - safe_proxy_docker
    ports:
      - "8931:80"

volumes:
  secret-key-volume:

# run `docker network create safe_proxy_docker`
# before running docker-compose up
networks:
  safe_proxy_docker:
    external: true
    driver: bridge
